{{- range $path, $_ := .Files.Glob "files/**.yaml" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cluster-api.crd-install.fullname" $ }}-{{ dir $path | base }}-{{ base $path | trimSuffix ".yaml" }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "cluster-api.crd-install.labels" $ | nindent 4 }}
  annotations:
    {{- include "cluster-api.crd-install.annotations" $ | nindent 4 }}
    helm.sh/hook-weight: "-1"
data:
  content: |
    {{- tpl ($.Files.Get $path) $ | nindent 4 }}
{{- end }}
