apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "cluster-api.crd-install.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-api.crd-install.labels" . | nindent 4 }}
  annotations:
    {{- include "cluster-api.crd-install.annotations" . | nindent 4 }}
    helm.sh/hook-weight: "-1"
spec:
  podSelector:
    matchLabels:
      {{- include "cluster-api.crd-install.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Egress
  egress:
  - ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 6443
