apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cluster-api.crd-install.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-api.crd-install.labels" . | nindent 4 }}
  annotations:
    {{- include "cluster-api.crd-install.annotations" . | nindent 4 }}
    helm.sh/hook-weight: "-2"
