apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: capi-kubeadm-control-plane-metrics-servicemonitor
  namespace: capi-kubeadm-control-plane-system
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      cluster.x-k8s.io/provider: control-plane-kubeadm