- op: replace
  path: /spec/versions/2/schema
  value:
    openAPIV3Schema:
      description: IPAddress is the Schema for the ipaddress API.
      properties:
        apiVersion:
          description: |-
            APIVersion defines the versioned schema of this representation of an object.
            Servers should convert recognized schemas to the latest internal value, and
            may reject unrecognized values.
            More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
          type: string
        kind:
          description: |-
            Kind is a string value representing the REST resource this object represents.
            Servers may infer this from the endpoint the client submits requests to.
            Cannot be updated.
            In CamelCase.
            More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
          type: string
        metadata:
          type: object
        spec:
          description: spec is the desired state of IPAddress.
          properties:
            address:
              description: address is the IP address.
              maxLength: 39
              minLength: 1
              type: string
            claimRef:
              description: claimRef is a reference to the claim this IPAddress was created for.
              properties:
                name:
                  description: |-
                    name of the IPAddressClaim.
                    name must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character.
                  maxLength: 253
                  minLength: 1
                  pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                  type: string
              required:
                - name
              type: object
            gateway:
              description: gateway is the network gateway of the network the address is from.
              maxLength: 39
              minLength: 1
              type: string
            poolRef:
              description: poolRef is a reference to the pool that this IPAddress was created from.
              properties:
                apiGroup:
                  description: |-
                    apiGroup of the IPPool.
                    apiGroup must be fully qualified domain name.
                  maxLength: 253
                  minLength: 1
                  pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                  type: string
                kind:
                  description: |-
                    kind of the IPPool.
                    kind must consist of alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character.
                  maxLength: 63
                  minLength: 1
                  pattern: ^[a-zA-Z]([-a-zA-Z0-9]*[a-zA-Z0-9])?$
                  type: string
                name:
                  description: |-
                    name of the IPPool.
                    name must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character.
                  maxLength: 253
                  minLength: 1
                  pattern: ^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$
                  type: string
              required:
                - apiGroup
                - kind
                - name
              type: object
            prefix:
              description: prefix is the prefix of the address.
              format: int32
              maximum: 128
              minimum: 0
              type: integer
          required:
            - address
            - claimRef
            - poolRef
            - prefix
          type: object
      required:
        - spec
      type: object
